PREFIX s:<http://sbols.org/v1#> 
CONSTRUCT {
?dc a s:DnaComponent;
    a ?type;
    s:displayId ?displayId;
    s:name ?name;
    s:description ?description;
    s:dnaSequence ?dna.
                  ?dna a s:DnaSequence;
                       s:nucleotides ?seq.
?dc s:annotations ?annotations.
                  ?annotations a s:SequenceAnnotation;
                               s:subComponent ?subComponent.
}
WHERE{
?dc a s:DnaComponent;
    s:displayId ?displayId.
OPTIONAL{ ?dc s:name ?name.}
OPTIONAL{ ?dc s:description ?description.}
OPTIONAL{ ?dc a+ ?type.}
OPTIONAL{ ?dc s:dnaSequence ?dna.
                            ?dna s:nucleotides ?seq;
                                 a s:DnaSequence.
}
OPTIONAL{ ?dc s:annotations ?annotations.
          ?annotations a s:SequenceAnnotation;
                         s:subComponent ?subComponent.
                                        ?subComponent a s:DnaComponent.
}
}
